name: Chushogi Random

on: [push, pull_request]

jobs:
  windows:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3

    - name: Install PyInstaller
      run: pip install pyinstaller
      
    - name: PyInstaller Windows
      run: |
        pyinstaller -D -F -n ChuShogi-Random -w "chushogi.py"

    - uses: actions/upload-artifact@v3
      with:
        name: ChuShogi Random (Windows)
        path: dist/ChuShogi-Random.exe

  linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: PyInstaller Linux
      run: |
        pyinstaller -D -F -n ChuShogi-Random -c "chushogi.py"

    - uses: actions/upload-artifact@v3
      with:
        name: ChuShogi Random (Linux)
        path: dist/ChuShogi-Random